# Generated by Django 5.0.3 on 2024-03-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=27)),
                ('f', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
