# Generated by Django 5.0.3 on 2024-03-07 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_texta_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='texta',
            options={'ordering': ['x']},
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.person')),
                ('employee_id', models.IntegerField()),
                ('department_id', models.IntegerField()),
            ],
            bases=('app.person',),
        ),
    ]
